version: "3"
services:
  ###################
  # Operations
  ###################
  # dd-statsd:
  #   container_name: dd-statsd
  #   image: datadog/docker-dd-agent:latest
  #   restart: unless-stopped
  #   ports:
  #     - 8125:8125/udp
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   env_file:
  #     - ./env/dd-statsd.env

  ####################
  # Core Services
  ####################
  force:
    container_name: force
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/force:production
    ports:
      - 5000:5000
    env_file:
      - ./env/secret/force.env
      - ./env/force.env
    depends_on:
      - redis-62

  metaphysics:
    container_name: metaphysics
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/metaphysics:production
    ports:
      - 3000:3000
    env_file:
      - ./env/secret/metaphysics.env
      - ./env/metaphysics.env
    depends_on:
      - memcached-14

  # gravity:
  #   container_name: gravity
  #   image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/gravity:production
  #   env_file:
  #     - ./env/secret/gravity.env

  ####################
  # Data Services
  ####################
  redis-62:
    container_name: redis-62
    image: redis:6.2.3
    ports:
      - "6379:6379"
    volumes:
      - redis-62:/data

  memcached-14:
    container_name: memcached-14
    image: memcached:1.4.34
    ports:
      - "11211:11211"

  # mongo-50:
  #   container_name: mongo-50
  #   hostname: mongo-50
  #   image: mongo:5.0.5
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-50:/data/db

  # postgres-96:
  #   container_name: postgres-96
  #   image: postgres:9.6
  #   env_file:
  #     - ./env/postgres-96.env
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-96:/var/lib/postgresql/data

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
  #   container_name: elasticsearch
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200

  localstack:
    container_name: localstack
    image: localstack/localstack:0.14.0
    env_file:
      - ./env/localstack.env
    ports:
      - "4567-4584:4567-4584"
      - "8042:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  localstack-setup:
    container_name: localstack-setup
    build:
      context: ./docker/localstack
    env_file:
      - ./env/localstack.env
    depends_on:
      - localstack

volumes:
  redis-62:
#   mongo-50:
#   postgres-96:
#   esdata:


